<?php
/**
 * ContactFieldApi
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use BSG\Api\V2\ApiException;
use BSG\Api\V2\Configuration;
use BSG\Api\V2\HeaderSelector;
use BSG\Api\V2\ObjectSerializer;

/**
 * ContactFieldApi Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ContactFieldApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'contactFieldCreate' => [
            'application/json',
        ],
        'contactFieldUpdate' => [
            'application/json',
        ],
        'contactFields' => [
            'application/json',
        ],
        'contactFieldsDeleteBatch' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation contactFieldCreate
     *
     * Create contact field
     *
     * @param  \BSG\Api\V2\Model\ContactFieldCreaterequest $contact_field_createrequest contact_field_createrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldCreate'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BSG\Api\V2\Model\ContactFieldCreate201response|\BSG\Api\V2\Model\Toomanyrequestsresponse
     */
    public function contactFieldCreate($contact_field_createrequest, string $contentType = self::contentTypes['contactFieldCreate'][0])
    {
        list($response) = $this->contactFieldCreateWithHttpInfo($contact_field_createrequest, $contentType);
        return $response;
    }

    /**
     * Operation contactFieldCreateWithHttpInfo
     *
     * Create contact field
     *
     * @param  \BSG\Api\V2\Model\ContactFieldCreaterequest $contact_field_createrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldCreate'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BSG\Api\V2\Model\ContactFieldCreate201response|\BSG\Api\V2\Model\Toomanyrequestsresponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function contactFieldCreateWithHttpInfo($contact_field_createrequest, string $contentType = self::contentTypes['contactFieldCreate'][0])
    {
        $request = $this->contactFieldCreateRequest($contact_field_createrequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('\BSG\Api\V2\Model\ContactFieldCreate201response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BSG\Api\V2\Model\ContactFieldCreate201response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BSG\Api\V2\Model\ContactFieldCreate201response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 429:
                    if ('\BSG\Api\V2\Model\Toomanyrequestsresponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BSG\Api\V2\Model\Toomanyrequestsresponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BSG\Api\V2\Model\Toomanyrequestsresponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\BSG\Api\V2\Model\ContactFieldCreate201response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BSG\Api\V2\Model\ContactFieldCreate201response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BSG\Api\V2\Model\Toomanyrequestsresponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contactFieldCreateAsync
     *
     * Create contact field
     *
     * @param  \BSG\Api\V2\Model\ContactFieldCreaterequest $contact_field_createrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldCreateAsync($contact_field_createrequest, string $contentType = self::contentTypes['contactFieldCreate'][0])
    {
        return $this->contactFieldCreateAsyncWithHttpInfo($contact_field_createrequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contactFieldCreateAsyncWithHttpInfo
     *
     * Create contact field
     *
     * @param  \BSG\Api\V2\Model\ContactFieldCreaterequest $contact_field_createrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldCreateAsyncWithHttpInfo($contact_field_createrequest, string $contentType = self::contentTypes['contactFieldCreate'][0])
    {
        $returnType = '\BSG\Api\V2\Model\ContactFieldCreate201response';
        $request = $this->contactFieldCreateRequest($contact_field_createrequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contactFieldCreate'
     *
     * @param  \BSG\Api\V2\Model\ContactFieldCreaterequest $contact_field_createrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contactFieldCreateRequest($contact_field_createrequest, string $contentType = self::contentTypes['contactFieldCreate'][0])
    {

        // verify the required parameter 'contact_field_createrequest' is set
        if ($contact_field_createrequest === null || (is_array($contact_field_createrequest) && count($contact_field_createrequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_field_createrequest when calling contactFieldCreate'
            );
        }


        $resourcePath = '/api/contacts/fields';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($contact_field_createrequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($contact_field_createrequest));
            } else {
                $httpBody = $contact_field_createrequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contactFieldUpdate
     *
     * Update contact field
     *
     * @param  int $id Contact field id (required)
     * @param  \BSG\Api\V2\Model\ContactFieldUpdaterequest $contact_field_updaterequest contact_field_updaterequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldUpdate'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BSG\Api\V2\Model\ContactFieldUpdate200response
     */
    public function contactFieldUpdate($id, $contact_field_updaterequest, string $contentType = self::contentTypes['contactFieldUpdate'][0])
    {
        list($response) = $this->contactFieldUpdateWithHttpInfo($id, $contact_field_updaterequest, $contentType);
        return $response;
    }

    /**
     * Operation contactFieldUpdateWithHttpInfo
     *
     * Update contact field
     *
     * @param  int $id Contact field id (required)
     * @param  \BSG\Api\V2\Model\ContactFieldUpdaterequest $contact_field_updaterequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldUpdate'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BSG\Api\V2\Model\ContactFieldUpdate200response, HTTP status code, HTTP response headers (array of strings)
     */
    public function contactFieldUpdateWithHttpInfo($id, $contact_field_updaterequest, string $contentType = self::contentTypes['contactFieldUpdate'][0])
    {
        $request = $this->contactFieldUpdateRequest($id, $contact_field_updaterequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\BSG\Api\V2\Model\ContactFieldUpdate200response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BSG\Api\V2\Model\ContactFieldUpdate200response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BSG\Api\V2\Model\ContactFieldUpdate200response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\BSG\Api\V2\Model\ContactFieldUpdate200response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BSG\Api\V2\Model\ContactFieldUpdate200response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contactFieldUpdateAsync
     *
     * Update contact field
     *
     * @param  int $id Contact field id (required)
     * @param  \BSG\Api\V2\Model\ContactFieldUpdaterequest $contact_field_updaterequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldUpdateAsync($id, $contact_field_updaterequest, string $contentType = self::contentTypes['contactFieldUpdate'][0])
    {
        return $this->contactFieldUpdateAsyncWithHttpInfo($id, $contact_field_updaterequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contactFieldUpdateAsyncWithHttpInfo
     *
     * Update contact field
     *
     * @param  int $id Contact field id (required)
     * @param  \BSG\Api\V2\Model\ContactFieldUpdaterequest $contact_field_updaterequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldUpdateAsyncWithHttpInfo($id, $contact_field_updaterequest, string $contentType = self::contentTypes['contactFieldUpdate'][0])
    {
        $returnType = '\BSG\Api\V2\Model\ContactFieldUpdate200response';
        $request = $this->contactFieldUpdateRequest($id, $contact_field_updaterequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contactFieldUpdate'
     *
     * @param  int $id Contact field id (required)
     * @param  \BSG\Api\V2\Model\ContactFieldUpdaterequest $contact_field_updaterequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contactFieldUpdateRequest($id, $contact_field_updaterequest, string $contentType = self::contentTypes['contactFieldUpdate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling contactFieldUpdate'
            );
        }

        // verify the required parameter 'contact_field_updaterequest' is set
        if ($contact_field_updaterequest === null || (is_array($contact_field_updaterequest) && count($contact_field_updaterequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_field_updaterequest when calling contactFieldUpdate'
            );
        }


        $resourcePath = '/api/contacts/fields/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($contact_field_updaterequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($contact_field_updaterequest));
            } else {
                $httpBody = $contact_field_updaterequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contactFields
     *
     * List of contact fields
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFields'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BSG\Api\V2\Model\ContactFieldCollectionSchema
     */
    public function contactFields(string $contentType = self::contentTypes['contactFields'][0])
    {
        list($response) = $this->contactFieldsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation contactFieldsWithHttpInfo
     *
     * List of contact fields
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFields'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BSG\Api\V2\Model\ContactFieldCollectionSchema, HTTP status code, HTTP response headers (array of strings)
     */
    public function contactFieldsWithHttpInfo(string $contentType = self::contentTypes['contactFields'][0])
    {
        $request = $this->contactFieldsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\BSG\Api\V2\Model\ContactFieldCollectionSchema' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\BSG\Api\V2\Model\ContactFieldCollectionSchema' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\BSG\Api\V2\Model\ContactFieldCollectionSchema', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\BSG\Api\V2\Model\ContactFieldCollectionSchema';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BSG\Api\V2\Model\ContactFieldCollectionSchema',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contactFieldsAsync
     *
     * List of contact fields
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFields'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldsAsync(string $contentType = self::contentTypes['contactFields'][0])
    {
        return $this->contactFieldsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contactFieldsAsyncWithHttpInfo
     *
     * List of contact fields
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFields'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldsAsyncWithHttpInfo(string $contentType = self::contentTypes['contactFields'][0])
    {
        $returnType = '\BSG\Api\V2\Model\ContactFieldCollectionSchema';
        $request = $this->contactFieldsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contactFields'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFields'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contactFieldsRequest(string $contentType = self::contentTypes['contactFields'][0])
    {


        $resourcePath = '/api/contacts/fields';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation contactFieldsDeleteBatch
     *
     * Delete contact fields by ids
     *
     * @param  \BSG\Api\V2\Model\ContactFieldsDeleteBatchrequest $contact_fields_delete_batchrequest contact_fields_delete_batchrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldsDeleteBatch'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return object
     */
    public function contactFieldsDeleteBatch($contact_fields_delete_batchrequest, string $contentType = self::contentTypes['contactFieldsDeleteBatch'][0])
    {
        list($response) = $this->contactFieldsDeleteBatchWithHttpInfo($contact_fields_delete_batchrequest, $contentType);
        return $response;
    }

    /**
     * Operation contactFieldsDeleteBatchWithHttpInfo
     *
     * Delete contact fields by ids
     *
     * @param  \BSG\Api\V2\Model\ContactFieldsDeleteBatchrequest $contact_fields_delete_batchrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldsDeleteBatch'] to see the possible values for this operation
     *
     * @throws \BSG\Api\V2\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function contactFieldsDeleteBatchWithHttpInfo($contact_fields_delete_batchrequest, string $contentType = self::contentTypes['contactFieldsDeleteBatch'][0])
    {
        $request = $this->contactFieldsDeleteBatchRequest($contact_fields_delete_batchrequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 204:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 204:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation contactFieldsDeleteBatchAsync
     *
     * Delete contact fields by ids
     *
     * @param  \BSG\Api\V2\Model\ContactFieldsDeleteBatchrequest $contact_fields_delete_batchrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldsDeleteBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldsDeleteBatchAsync($contact_fields_delete_batchrequest, string $contentType = self::contentTypes['contactFieldsDeleteBatch'][0])
    {
        return $this->contactFieldsDeleteBatchAsyncWithHttpInfo($contact_fields_delete_batchrequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation contactFieldsDeleteBatchAsyncWithHttpInfo
     *
     * Delete contact fields by ids
     *
     * @param  \BSG\Api\V2\Model\ContactFieldsDeleteBatchrequest $contact_fields_delete_batchrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldsDeleteBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function contactFieldsDeleteBatchAsyncWithHttpInfo($contact_fields_delete_batchrequest, string $contentType = self::contentTypes['contactFieldsDeleteBatch'][0])
    {
        $returnType = 'object';
        $request = $this->contactFieldsDeleteBatchRequest($contact_fields_delete_batchrequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'contactFieldsDeleteBatch'
     *
     * @param  \BSG\Api\V2\Model\ContactFieldsDeleteBatchrequest $contact_fields_delete_batchrequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['contactFieldsDeleteBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function contactFieldsDeleteBatchRequest($contact_fields_delete_batchrequest, string $contentType = self::contentTypes['contactFieldsDeleteBatch'][0])
    {

        // verify the required parameter 'contact_fields_delete_batchrequest' is set
        if ($contact_fields_delete_batchrequest === null || (is_array($contact_fields_delete_batchrequest) && count($contact_fields_delete_batchrequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $contact_fields_delete_batchrequest when calling contactFieldsDeleteBatch'
            );
        }


        $resourcePath = '/api/contacts/fields/delete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($contact_fields_delete_batchrequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($contact_fields_delete_batchrequest));
            } else {
                $httpBody = $contact_fields_delete_batchrequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
