<?php
/**
 * MessageUniversal
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;

use \ArrayAccess;
use \BSG\Api\V2\ObjectSerializer;

/**
 * MessageUniversal Class Doc Comment
 *
 * @category Class
 * @description A message that can be of type SMS, WhatsApp, or RCS.
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MessageUniversal implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MessageUniversal';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'channels' => 'string[]',
        'phone' => '\BSG\Api\V2\Model\Phone',
        'rcs' => '\BSG\Api\V2\Model\Rcs',
        'viber' => '\BSG\Api\V2\Model\Viber',
        'sms' => '\BSG\Api\V2\Model\Sms',
        'voice' => '\BSG\Api\V2\Model\Voice',
        'telegram' => '\BSG\Api\V2\Model\Telegram',
        'callback_url' => 'mixed',
        'tariff_code' => 'int',
        'validity' => 'int',
        'validity_seconds' => 'int',
        'respect_curfew' => 'bool',
        'add_to_contact_book' => 'bool',
        'check_stop_list' => 'bool',
        'dry_run' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'channels' => null,
        'phone' => null,
        'rcs' => null,
        'viber' => null,
        'sms' => null,
        'voice' => null,
        'telegram' => null,
        'callback_url' => null,
        'tariff_code' => null,
        'validity' => null,
        'validity_seconds' => null,
        'respect_curfew' => null,
        'add_to_contact_book' => null,
        'check_stop_list' => null,
        'dry_run' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'channels' => false,
        'phone' => false,
        'rcs' => false,
        'viber' => false,
        'sms' => false,
        'voice' => false,
        'telegram' => false,
        'callback_url' => true,
        'tariff_code' => false,
        'validity' => false,
        'validity_seconds' => false,
        'respect_curfew' => false,
        'add_to_contact_book' => false,
        'check_stop_list' => false,
        'dry_run' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'channels' => 'channels',
        'phone' => 'phone',
        'rcs' => 'rcs',
        'viber' => 'viber',
        'sms' => 'sms',
        'voice' => 'voice',
        'telegram' => 'telegram',
        'callback_url' => 'callback_url',
        'tariff_code' => 'tariff_code',
        'validity' => 'validity',
        'validity_seconds' => 'validity_seconds',
        'respect_curfew' => 'respect_curfew',
        'add_to_contact_book' => 'add_to_contact_book',
        'check_stop_list' => 'check_stop_list',
        'dry_run' => 'dry_run'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'channels' => 'setChannels',
        'phone' => 'setPhone',
        'rcs' => 'setRcs',
        'viber' => 'setViber',
        'sms' => 'setSms',
        'voice' => 'setVoice',
        'telegram' => 'setTelegram',
        'callback_url' => 'setCallbackUrl',
        'tariff_code' => 'setTariffCode',
        'validity' => 'setValidity',
        'validity_seconds' => 'setValiditySeconds',
        'respect_curfew' => 'setRespectCurfew',
        'add_to_contact_book' => 'setAddToContactBook',
        'check_stop_list' => 'setCheckStopList',
        'dry_run' => 'setDryRun'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'channels' => 'getChannels',
        'phone' => 'getPhone',
        'rcs' => 'getRcs',
        'viber' => 'getViber',
        'sms' => 'getSms',
        'voice' => 'getVoice',
        'telegram' => 'getTelegram',
        'callback_url' => 'getCallbackUrl',
        'tariff_code' => 'getTariffCode',
        'validity' => 'getValidity',
        'validity_seconds' => 'getValiditySeconds',
        'respect_curfew' => 'getRespectCurfew',
        'add_to_contact_book' => 'getAddToContactBook',
        'check_stop_list' => 'getCheckStopList',
        'dry_run' => 'getDryRun'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CHANNELS_SMS = 'sms';
    public const CHANNELS_RCS = 'rcs';
    public const CHANNELS_VIBER = 'viber';
    public const CHANNELS_VOICE = 'voice';
    public const CHANNELS_TELEGRAM = 'telegram';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChannelsAllowableValues()
    {
        return [
            self::CHANNELS_SMS,
            self::CHANNELS_RCS,
            self::CHANNELS_VIBER,
            self::CHANNELS_VOICE,
            self::CHANNELS_TELEGRAM,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('channels', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('rcs', $data ?? [], null);
        $this->setIfExists('viber', $data ?? [], null);
        $this->setIfExists('sms', $data ?? [], null);
        $this->setIfExists('voice', $data ?? [], null);
        $this->setIfExists('telegram', $data ?? [], null);
        $this->setIfExists('callback_url', $data ?? [], null);
        $this->setIfExists('tariff_code', $data ?? [], null);
        $this->setIfExists('validity', $data ?? [], 72);
        $this->setIfExists('validity_seconds', $data ?? [], null);
        $this->setIfExists('respect_curfew', $data ?? [], false);
        $this->setIfExists('add_to_contact_book', $data ?? [], true);
        $this->setIfExists('check_stop_list', $data ?? [], true);
        $this->setIfExists('dry_run', $data ?? [], false);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['channels'] === null) {
            $invalidProperties[] = "'channels' can't be null";
        }
        if ((count($this->container['channels']) > 2)) {
            $invalidProperties[] = "invalid value for 'channels', number of items must be less than or equal to 2.";
        }

        if ((count($this->container['channels']) < 1)) {
            $invalidProperties[] = "invalid value for 'channels', number of items must be greater than or equal to 1.";
        }

        if ($this->container['phone'] === null) {
            $invalidProperties[] = "'phone' can't be null";
        }
        if (!is_null($this->container['callback_url']) && (mb_strlen($this->container['callback_url']) > 100)) {
            $invalidProperties[] = "invalid value for 'callback_url', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['validity']) && ($this->container['validity'] > 72)) {
            $invalidProperties[] = "invalid value for 'validity', must be smaller than or equal to 72.";
        }

        if (!is_null($this->container['validity']) && ($this->container['validity'] < 1)) {
            $invalidProperties[] = "invalid value for 'validity', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['validity_seconds']) && ($this->container['validity_seconds'] > 86400)) {
            $invalidProperties[] = "invalid value for 'validity_seconds', must be smaller than or equal to 86400.";
        }

        if (!is_null($this->container['validity_seconds']) && ($this->container['validity_seconds'] < 30)) {
            $invalidProperties[] = "invalid value for 'validity_seconds', must be bigger than or equal to 30.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets channels
     *
     * @return string[]
     */
    public function getChannels()
    {
        return $this->container['channels'];
    }

    /**
     * Sets channels
     *
     * @param string[] $channels channels
     *
     * @return self
     */
    public function setChannels($channels)
    {
        if (is_null($channels)) {
            throw new \InvalidArgumentException('non-nullable channels cannot be null');
        }
        $allowedValues = $this->getChannelsAllowableValues();
        if (array_diff($channels, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'channels', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }

        if ((count($channels) > 2)) {
            throw new \InvalidArgumentException('invalid value for $channels when calling MessageUniversal., number of items must be less than or equal to 2.');
        }
        if ((count($channels) < 1)) {
            throw new \InvalidArgumentException('invalid length for $channels when calling MessageUniversal., number of items must be greater than or equal to 1.');
        }
        $this->container['channels'] = $channels;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return \BSG\Api\V2\Model\Phone
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param \BSG\Api\V2\Model\Phone $phone phone
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            throw new \InvalidArgumentException('non-nullable phone cannot be null');
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets rcs
     *
     * @return \BSG\Api\V2\Model\Rcs|null
     */
    public function getRcs()
    {
        return $this->container['rcs'];
    }

    /**
     * Sets rcs
     *
     * @param \BSG\Api\V2\Model\Rcs|null $rcs rcs
     *
     * @return self
     */
    public function setRcs($rcs)
    {
        if (is_null($rcs)) {
            throw new \InvalidArgumentException('non-nullable rcs cannot be null');
        }
        $this->container['rcs'] = $rcs;

        return $this;
    }

    /**
     * Gets viber
     *
     * @return \BSG\Api\V2\Model\Viber|null
     */
    public function getViber()
    {
        return $this->container['viber'];
    }

    /**
     * Sets viber
     *
     * @param \BSG\Api\V2\Model\Viber|null $viber viber
     *
     * @return self
     */
    public function setViber($viber)
    {
        if (is_null($viber)) {
            throw new \InvalidArgumentException('non-nullable viber cannot be null');
        }
        $this->container['viber'] = $viber;

        return $this;
    }

    /**
     * Gets sms
     *
     * @return \BSG\Api\V2\Model\Sms|null
     */
    public function getSms()
    {
        return $this->container['sms'];
    }

    /**
     * Sets sms
     *
     * @param \BSG\Api\V2\Model\Sms|null $sms sms
     *
     * @return self
     */
    public function setSms($sms)
    {
        if (is_null($sms)) {
            throw new \InvalidArgumentException('non-nullable sms cannot be null');
        }
        $this->container['sms'] = $sms;

        return $this;
    }

    /**
     * Gets voice
     *
     * @return \BSG\Api\V2\Model\Voice|null
     */
    public function getVoice()
    {
        return $this->container['voice'];
    }

    /**
     * Sets voice
     *
     * @param \BSG\Api\V2\Model\Voice|null $voice voice
     *
     * @return self
     */
    public function setVoice($voice)
    {
        if (is_null($voice)) {
            throw new \InvalidArgumentException('non-nullable voice cannot be null');
        }
        $this->container['voice'] = $voice;

        return $this;
    }

    /**
     * Gets telegram
     *
     * @return \BSG\Api\V2\Model\Telegram|null
     */
    public function getTelegram()
    {
        return $this->container['telegram'];
    }

    /**
     * Sets telegram
     *
     * @param \BSG\Api\V2\Model\Telegram|null $telegram telegram
     *
     * @return self
     */
    public function setTelegram($telegram)
    {
        if (is_null($telegram)) {
            throw new \InvalidArgumentException('non-nullable telegram cannot be null');
        }
        $this->container['telegram'] = $telegram;

        return $this;
    }

    /**
     * Gets callback_url
     *
     * @return mixed|null
     */
    public function getCallbackUrl()
    {
        return $this->container['callback_url'];
    }

    /**
     * Sets callback_url
     *
     * @param mixed|null $callback_url Link to get the delivery status of messages. If this parameter is specified in the method, it will take precedence over the value specified in the “Callback URL” field in the Personal Area.
     *
     * @return self
     */
    public function setCallbackUrl($callback_url)
    {
        if (is_null($callback_url)) {
            array_push($this->openAPINullablesSetToNull, 'callback_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('callback_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($callback_url) && (mb_strlen($callback_url) > 100)) {
            throw new \InvalidArgumentException('invalid length for $callback_url when calling MessageUniversal., must be smaller than or equal to 100.');
        }

        $this->container['callback_url'] = $callback_url;

        return $this;
    }

    /**
     * Gets tariff_code
     *
     * @return int|null
     */
    public function getTariffCode()
    {
        return $this->container['tariff_code'];
    }

    /**
     * Sets tariff_code
     *
     * @param int|null $tariff_code Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     *
     * @return self
     */
    public function setTariffCode($tariff_code)
    {
        if (is_null($tariff_code)) {
            throw new \InvalidArgumentException('non-nullable tariff_code cannot be null');
        }
        $this->container['tariff_code'] = $tariff_code;

        return $this;
    }

    /**
     * Gets validity
     *
     * @return int|null
     */
    public function getValidity()
    {
        return $this->container['validity'];
    }

    /**
     * Sets validity
     *
     * @param int|null $validity validity time in hours. The default is 72 hours. Integer from 1 to 72
     *
     * @return self
     */
    public function setValidity($validity)
    {
        if (is_null($validity)) {
            throw new \InvalidArgumentException('non-nullable validity cannot be null');
        }

        if (($validity > 72)) {
            throw new \InvalidArgumentException('invalid value for $validity when calling MessageUniversal., must be smaller than or equal to 72.');
        }
        if (($validity < 1)) {
            throw new \InvalidArgumentException('invalid value for $validity when calling MessageUniversal., must be bigger than or equal to 1.');
        }

        $this->container['validity'] = $validity;

        return $this;
    }

    /**
     * Gets validity_seconds
     *
     * @return int|null
     */
    public function getValiditySeconds()
    {
        return $this->container['validity_seconds'];
    }

    /**
     * Sets validity_seconds
     *
     * @param int|null $validity_seconds Message validity period in seconds. After this period expires, the message will be in **EXPIRED** status or will be redirected to the SMS channel if it was specified in the request. Incompatible with **validity**
     *
     * @return self
     */
    public function setValiditySeconds($validity_seconds)
    {
        if (is_null($validity_seconds)) {
            throw new \InvalidArgumentException('non-nullable validity_seconds cannot be null');
        }

        if (($validity_seconds > 86400)) {
            throw new \InvalidArgumentException('invalid value for $validity_seconds when calling MessageUniversal., must be smaller than or equal to 86400.');
        }
        if (($validity_seconds < 30)) {
            throw new \InvalidArgumentException('invalid value for $validity_seconds when calling MessageUniversal., must be bigger than or equal to 30.');
        }

        $this->container['validity_seconds'] = $validity_seconds;

        return $this;
    }

    /**
     * Gets respect_curfew
     *
     * @return bool|null
     */
    public function getRespectCurfew()
    {
        return $this->container['respect_curfew'];
    }

    /**
     * Sets respect_curfew
     *
     * @param bool|null $respect_curfew Check the curfew if it's set up in user settings.
     *
     * @return self
     */
    public function setRespectCurfew($respect_curfew)
    {
        if (is_null($respect_curfew)) {
            throw new \InvalidArgumentException('non-nullable respect_curfew cannot be null');
        }
        $this->container['respect_curfew'] = $respect_curfew;

        return $this;
    }

    /**
     * Gets add_to_contact_book
     *
     * @return bool|null
     */
    public function getAddToContactBook()
    {
        return $this->container['add_to_contact_book'];
    }

    /**
     * Sets add_to_contact_book
     *
     * @param bool|null $add_to_contact_book Specifies whether to add the specified phone number of the message recipient to the contact book
     *
     * @return self
     */
    public function setAddToContactBook($add_to_contact_book)
    {
        if (is_null($add_to_contact_book)) {
            throw new \InvalidArgumentException('non-nullable add_to_contact_book cannot be null');
        }
        $this->container['add_to_contact_book'] = $add_to_contact_book;

        return $this;
    }

    /**
     * Gets check_stop_list
     *
     * @return bool|null
     */
    public function getCheckStopList()
    {
        return $this->container['check_stop_list'];
    }

    /**
     * Sets check_stop_list
     *
     * @param bool|null $check_stop_list Check the recipient’s phone number for being in the stop list.  Possible values:    - true – if the number is found in the stop list, do not send the message  - false – ignore the stop list
     *
     * @return self
     */
    public function setCheckStopList($check_stop_list)
    {
        if (is_null($check_stop_list)) {
            throw new \InvalidArgumentException('non-nullable check_stop_list cannot be null');
        }
        $this->container['check_stop_list'] = $check_stop_list;

        return $this;
    }

    /**
     * Gets dry_run
     *
     * @return bool|null
     */
    public function getDryRun()
    {
        return $this->container['dry_run'];
    }

    /**
     * Sets dry_run
     *
     * @param bool|null $dry_run Allows you to check the validity of the request without actual message sending
     *
     * @return self
     */
    public function setDryRun($dry_run)
    {
        if (is_null($dry_run)) {
            array_push($this->openAPINullablesSetToNull, 'dry_run');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dry_run', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dry_run'] = $dry_run;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


