<?php
/**
 * SendViberCampaign
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;

use \ArrayAccess;
use \BSG\Api\V2\ObjectSerializer;

/**
 * SendViberCampaign Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SendViberCampaign implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SendViberCampaign';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'phones' => '\BSG\Api\V2\Model\Phone[]',
        'sender' => 'string',
        'text' => 'string',
        'image_url' => 'string',
        'button_caption' => 'string',
        'link_url' => 'string',
        'start_at' => '\DateTime',
        'tariff_code' => 'int',
        'validity' => 'int',
        'alternative_channel' => '\BSG\Api\V2\Model\AlternativeChannel',
        'add_to_contact_book' => 'bool',
        'check_stop_list' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'phones' => null,
        'sender' => null,
        'text' => null,
        'image_url' => null,
        'button_caption' => null,
        'link_url' => 'url',
        'start_at' => 'date-time',
        'tariff_code' => null,
        'validity' => null,
        'alternative_channel' => null,
        'add_to_contact_book' => null,
        'check_stop_list' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'phones' => false,
        'sender' => false,
        'text' => false,
        'image_url' => false,
        'button_caption' => false,
        'link_url' => false,
        'start_at' => false,
        'tariff_code' => false,
        'validity' => false,
        'alternative_channel' => false,
        'add_to_contact_book' => false,
        'check_stop_list' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'phones' => 'phones',
        'sender' => 'sender',
        'text' => 'text',
        'image_url' => 'image_url',
        'button_caption' => 'button_caption',
        'link_url' => 'link_url',
        'start_at' => 'start_at',
        'tariff_code' => 'tariff_code',
        'validity' => 'validity',
        'alternative_channel' => 'alternative_channel',
        'add_to_contact_book' => 'add_to_contact_book',
        'check_stop_list' => 'check_stop_list'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'phones' => 'setPhones',
        'sender' => 'setSender',
        'text' => 'setText',
        'image_url' => 'setImageUrl',
        'button_caption' => 'setButtonCaption',
        'link_url' => 'setLinkUrl',
        'start_at' => 'setStartAt',
        'tariff_code' => 'setTariffCode',
        'validity' => 'setValidity',
        'alternative_channel' => 'setAlternativeChannel',
        'add_to_contact_book' => 'setAddToContactBook',
        'check_stop_list' => 'setCheckStopList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'phones' => 'getPhones',
        'sender' => 'getSender',
        'text' => 'getText',
        'image_url' => 'getImageUrl',
        'button_caption' => 'getButtonCaption',
        'link_url' => 'getLinkUrl',
        'start_at' => 'getStartAt',
        'tariff_code' => 'getTariffCode',
        'validity' => 'getValidity',
        'alternative_channel' => 'getAlternativeChannel',
        'add_to_contact_book' => 'getAddToContactBook',
        'check_stop_list' => 'getCheckStopList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('phones', $data ?? [], null);
        $this->setIfExists('sender', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('button_caption', $data ?? [], null);
        $this->setIfExists('link_url', $data ?? [], null);
        $this->setIfExists('start_at', $data ?? [], null);
        $this->setIfExists('tariff_code', $data ?? [], null);
        $this->setIfExists('validity', $data ?? [], 72);
        $this->setIfExists('alternative_channel', $data ?? [], null);
        $this->setIfExists('add_to_contact_book', $data ?? [], true);
        $this->setIfExists('check_stop_list', $data ?? [], true);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['phones'] === null) {
            $invalidProperties[] = "'phones' can't be null";
        }
        if ((count($this->container['phones']) > 5000)) {
            $invalidProperties[] = "invalid value for 'phones', number of items must be less than or equal to 5000.";
        }

        if ((count($this->container['phones']) < 1)) {
            $invalidProperties[] = "invalid value for 'phones', number of items must be greater than or equal to 1.";
        }

        if ($this->container['sender'] === null) {
            $invalidProperties[] = "'sender' can't be null";
        }
        if ($this->container['text'] === null) {
            $invalidProperties[] = "'text' can't be null";
        }
        if ((mb_strlen($this->container['text']) > 1000)) {
            $invalidProperties[] = "invalid value for 'text', the character length must be smaller than or equal to 1000.";
        }

        if ((mb_strlen($this->container['text']) < 1)) {
            $invalidProperties[] = "invalid value for 'text', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['image_url']) && (mb_strlen($this->container['image_url']) > 255)) {
            $invalidProperties[] = "invalid value for 'image_url', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['image_url']) && !preg_match("/^(http|https)://([A-Z0-9][A-Z0-9_-]*)(\\.[A-Z0-9][A-Z0-9_-]*)+(:(\\d+))?([-_/A-Z0-9?=&]*)?(\\.jpg|\\.png|\\.tiff|\\.jpeg|\\.gif|\\.bmp){1}$/iD", $this->container['image_url'])) {
            $invalidProperties[] = "invalid value for 'image_url', must be conform to the pattern /^(http|https)://([A-Z0-9][A-Z0-9_-]*)(\\.[A-Z0-9][A-Z0-9_-]*)+(:(\\d+))?([-_/A-Z0-9?=&]*)?(\\.jpg|\\.png|\\.tiff|\\.jpeg|\\.gif|\\.bmp){1}$/iD.";
        }

        if (!is_null($this->container['button_caption']) && (mb_strlen($this->container['button_caption']) > 20)) {
            $invalidProperties[] = "invalid value for 'button_caption', the character length must be smaller than or equal to 20.";
        }

        if (!is_null($this->container['link_url']) && (mb_strlen($this->container['link_url']) > 255)) {
            $invalidProperties[] = "invalid value for 'link_url', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['link_url']) && !preg_match("/^(https?://)?([\\p{L}\\d\\.-]+)\\.([\\p{L}\\.]{2,50})([/\\w \\.-]*)*_/?/iu", $this->container['link_url'])) {
            $invalidProperties[] = "invalid value for 'link_url', must be conform to the pattern /^(https?://)?([\\p{L}\\d\\.-]+)\\.([\\p{L}\\.]{2,50})([/\\w \\.-]*)*_/?/iu.";
        }

        if (!is_null($this->container['validity']) && ($this->container['validity'] > 72)) {
            $invalidProperties[] = "invalid value for 'validity', must be smaller than or equal to 72.";
        }

        if (!is_null($this->container['validity']) && ($this->container['validity'] < 1)) {
            $invalidProperties[] = "invalid value for 'validity', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets phones
     *
     * @return \BSG\Api\V2\Model\Phone[]
     */
    public function getPhones()
    {
        return $this->container['phones'];
    }

    /**
     * Sets phones
     *
     * @param \BSG\Api\V2\Model\Phone[] $phones The list of objects containing information about the mobile phone number (number) and (reference_id) to send a message to
     *
     * @return self
     */
    public function setPhones($phones)
    {
        if (is_null($phones)) {
            throw new \InvalidArgumentException('non-nullable phones cannot be null');
        }

        if ((count($phones) > 5000)) {
            throw new \InvalidArgumentException('invalid value for $phones when calling SendViberCampaign., number of items must be less than or equal to 5000.');
        }
        if ((count($phones) < 1)) {
            throw new \InvalidArgumentException('invalid length for $phones when calling SendViberCampaign., number of items must be greater than or equal to 1.');
        }
        $this->container['phones'] = $phones;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return string
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param string $sender Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
     *
     * @return self
     */
    public function setSender($sender)
    {
        if (is_null($sender)) {
            throw new \InvalidArgumentException('non-nullable sender cannot be null');
        }
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string $text text
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        if ((mb_strlen($text) > 1000)) {
            throw new \InvalidArgumentException('invalid length for $text when calling SendViberCampaign., must be smaller than or equal to 1000.');
        }
        if ((mb_strlen($text) < 1)) {
            throw new \InvalidArgumentException('invalid length for $text when calling SendViberCampaign., must be bigger than or equal to 1.');
        }

        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string|null
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string|null $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            throw new \InvalidArgumentException('non-nullable image_url cannot be null');
        }
        if ((mb_strlen($image_url) > 255)) {
            throw new \InvalidArgumentException('invalid length for $image_url when calling SendViberCampaign., must be smaller than or equal to 255.');
        }
        if ((!preg_match("/^(http|https)://([A-Z0-9][A-Z0-9_-]*)(\\.[A-Z0-9][A-Z0-9_-]*)+(:(\\d+))?([-_/A-Z0-9?=&]*)?(\\.jpg|\\.png|\\.tiff|\\.jpeg|\\.gif|\\.bmp){1}$/iD", ObjectSerializer::toString($image_url)))) {
            throw new \InvalidArgumentException("invalid value for \$image_url when calling SendViberCampaign., must conform to the pattern /^(http|https)://([A-Z0-9][A-Z0-9_-]*)(\\.[A-Z0-9][A-Z0-9_-]*)+(:(\\d+))?([-_/A-Z0-9?=&]*)?(\\.jpg|\\.png|\\.tiff|\\.jpeg|\\.gif|\\.bmp){1}$/iD.");
        }

        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets button_caption
     *
     * @return string|null
     */
    public function getButtonCaption()
    {
        return $this->container['button_caption'];
    }

    /**
     * Sets button_caption
     *
     * @param string|null $button_caption button_caption
     *
     * @return self
     */
    public function setButtonCaption($button_caption)
    {
        if (is_null($button_caption)) {
            throw new \InvalidArgumentException('non-nullable button_caption cannot be null');
        }
        if ((mb_strlen($button_caption) > 20)) {
            throw new \InvalidArgumentException('invalid length for $button_caption when calling SendViberCampaign., must be smaller than or equal to 20.');
        }

        $this->container['button_caption'] = $button_caption;

        return $this;
    }

    /**
     * Gets link_url
     *
     * @return string|null
     */
    public function getLinkUrl()
    {
        return $this->container['link_url'];
    }

    /**
     * Sets link_url
     *
     * @param string|null $link_url Required if button_caption is set
     *
     * @return self
     */
    public function setLinkUrl($link_url)
    {
        if (is_null($link_url)) {
            throw new \InvalidArgumentException('non-nullable link_url cannot be null');
        }
        if ((mb_strlen($link_url) > 255)) {
            throw new \InvalidArgumentException('invalid length for $link_url when calling SendViberCampaign., must be smaller than or equal to 255.');
        }
        if ((!preg_match("/^(https?://)?([\\p{L}\\d\\.-]+)\\.([\\p{L}\\.]{2,50})([/\\w \\.-]*)*_/?/iu", ObjectSerializer::toString($link_url)))) {
            throw new \InvalidArgumentException("invalid value for \$link_url when calling SendViberCampaign., must conform to the pattern /^(https?://)?([\\p{L}\\d\\.-]+)\\.([\\p{L}\\.]{2,50})([/\\w \\.-]*)*_/?/iu.");
        }

        $this->container['link_url'] = $link_url;

        return $this;
    }

    /**
     * Gets start_at
     *
     * @return \DateTime|null
     */
    public function getStartAt()
    {
        return $this->container['start_at'];
    }

    /**
     * Sets start_at
     *
     * @param \DateTime|null $start_at Start sending the messages at
     *
     * @return self
     */
    public function setStartAt($start_at)
    {
        if (is_null($start_at)) {
            throw new \InvalidArgumentException('non-nullable start_at cannot be null');
        }
        $this->container['start_at'] = $start_at;

        return $this;
    }

    /**
     * Gets tariff_code
     *
     * @return int|null
     */
    public function getTariffCode()
    {
        return $this->container['tariff_code'];
    }

    /**
     * Sets tariff_code
     *
     * @param int|null $tariff_code Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
     *
     * @return self
     */
    public function setTariffCode($tariff_code)
    {
        if (is_null($tariff_code)) {
            throw new \InvalidArgumentException('non-nullable tariff_code cannot be null');
        }
        $this->container['tariff_code'] = $tariff_code;

        return $this;
    }

    /**
     * Gets validity
     *
     * @return int|null
     */
    public function getValidity()
    {
        return $this->container['validity'];
    }

    /**
     * Sets validity
     *
     * @param int|null $validity validity time in hours. The default is 72 hours. Integer from 1 to 72
     *
     * @return self
     */
    public function setValidity($validity)
    {
        if (is_null($validity)) {
            throw new \InvalidArgumentException('non-nullable validity cannot be null');
        }

        if (($validity > 72)) {
            throw new \InvalidArgumentException('invalid value for $validity when calling SendViberCampaign., must be smaller than or equal to 72.');
        }
        if (($validity < 1)) {
            throw new \InvalidArgumentException('invalid value for $validity when calling SendViberCampaign., must be bigger than or equal to 1.');
        }

        $this->container['validity'] = $validity;

        return $this;
    }

    /**
     * Gets alternative_channel
     *
     * @return \BSG\Api\V2\Model\AlternativeChannel|null
     */
    public function getAlternativeChannel()
    {
        return $this->container['alternative_channel'];
    }

    /**
     * Sets alternative_channel
     *
     * @param \BSG\Api\V2\Model\AlternativeChannel|null $alternative_channel alternative_channel
     *
     * @return self
     */
    public function setAlternativeChannel($alternative_channel)
    {
        if (is_null($alternative_channel)) {
            throw new \InvalidArgumentException('non-nullable alternative_channel cannot be null');
        }
        $this->container['alternative_channel'] = $alternative_channel;

        return $this;
    }

    /**
     * Gets add_to_contact_book
     *
     * @return bool|null
     */
    public function getAddToContactBook()
    {
        return $this->container['add_to_contact_book'];
    }

    /**
     * Sets add_to_contact_book
     *
     * @param bool|null $add_to_contact_book Specifies whether to add the specified phone number of the message recipient to the contact book
     *
     * @return self
     */
    public function setAddToContactBook($add_to_contact_book)
    {
        if (is_null($add_to_contact_book)) {
            throw new \InvalidArgumentException('non-nullable add_to_contact_book cannot be null');
        }
        $this->container['add_to_contact_book'] = $add_to_contact_book;

        return $this;
    }

    /**
     * Gets check_stop_list
     *
     * @return bool|null
     */
    public function getCheckStopList()
    {
        return $this->container['check_stop_list'];
    }

    /**
     * Sets check_stop_list
     *
     * @param bool|null $check_stop_list Check the recipient’s phone number for being in the stop list.  Possible values:    - true – if the number is found in the stop list, do not send the message  - false – ignore the stop list
     *
     * @return self
     */
    public function setCheckStopList($check_stop_list)
    {
        if (is_null($check_stop_list)) {
            throw new \InvalidArgumentException('non-nullable check_stop_list cannot be null');
        }
        $this->container['check_stop_list'] = $check_stop_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


