<?php
/**
 * StatJobsCreateRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * One-API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BSG\Api\V2\Model;

use \ArrayAccess;
use \BSG\Api\V2\ObjectSerializer;

/**
 * StatJobsCreateRequest Class Doc Comment
 *
 * @category Class
 * @package  BSG\Api\V2
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StatJobsCreateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'type';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StatJobsCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'type' => 'string',
        'message_id' => 'int[]',
        'time_in_from' => '\DateTime',
        'time_in_to' => '\DateTime',
        'time_sent_from' => '\DateTime',
        'time_sent_to' => '\DateTime',
        'phones' => 'int[]',
        'sender' => 'string',
        'source' => 'string',
        'country' => 'string',
        'operator_id' => 'string',
        'status' => 'string',
        'sl_clicks' => 'string',
        'sl_clicks_comp' => 'string',
        'sl_clicks_count' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'type' => null,
        'message_id' => null,
        'time_in_from' => 'date-time',
        'time_in_to' => 'date-time',
        'time_sent_from' => 'date-time',
        'time_sent_to' => 'date-time',
        'phones' => null,
        'sender' => null,
        'source' => null,
        'country' => null,
        'operator_id' => null,
        'status' => null,
        'sl_clicks' => null,
        'sl_clicks_comp' => null,
        'sl_clicks_count' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'type' => false,
        'message_id' => false,
        'time_in_from' => false,
        'time_in_to' => false,
        'time_sent_from' => false,
        'time_sent_to' => false,
        'phones' => false,
        'sender' => false,
        'source' => false,
        'country' => false,
        'operator_id' => false,
        'status' => false,
        'sl_clicks' => false,
        'sl_clicks_comp' => false,
        'sl_clicks_count' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'message_id' => 'message_id',
        'time_in_from' => 'time_in_from',
        'time_in_to' => 'time_in_to',
        'time_sent_from' => 'time_sent_from',
        'time_sent_to' => 'time_sent_to',
        'phones' => 'phones',
        'sender' => 'sender',
        'source' => 'source',
        'country' => 'country',
        'operator_id' => 'operator_id',
        'status' => 'status',
        'sl_clicks' => 'sl_clicks',
        'sl_clicks_comp' => 'sl_clicks_comp',
        'sl_clicks_count' => 'sl_clicks_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'message_id' => 'setMessageId',
        'time_in_from' => 'setTimeInFrom',
        'time_in_to' => 'setTimeInTo',
        'time_sent_from' => 'setTimeSentFrom',
        'time_sent_to' => 'setTimeSentTo',
        'phones' => 'setPhones',
        'sender' => 'setSender',
        'source' => 'setSource',
        'country' => 'setCountry',
        'operator_id' => 'setOperatorId',
        'status' => 'setStatus',
        'sl_clicks' => 'setSlClicks',
        'sl_clicks_comp' => 'setSlClicksComp',
        'sl_clicks_count' => 'setSlClicksCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'message_id' => 'getMessageId',
        'time_in_from' => 'getTimeInFrom',
        'time_in_to' => 'getTimeInTo',
        'time_sent_from' => 'getTimeSentFrom',
        'time_sent_to' => 'getTimeSentTo',
        'phones' => 'getPhones',
        'sender' => 'getSender',
        'source' => 'getSource',
        'country' => 'getCountry',
        'operator_id' => 'getOperatorId',
        'status' => 'getStatus',
        'sl_clicks' => 'getSlClicks',
        'sl_clicks_comp' => 'getSlClicksComp',
        'sl_clicks_count' => 'getSlClicksCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_MESSAGE = 'message';
    public const TYPE_PARAMS = 'params';
    public const SENDER_API = 'api';
    public const SENDER_WEB = 'web';
    public const SENDER_SMPP = 'smpp';
    public const SENDER_XML = 'xml';
    public const SENDER_HTTP = 'http';
    public const SENDER_JSON = 'json';
    public const SOURCE_API = 'api';
    public const SOURCE_WEB = 'web';
    public const SOURCE_SMPP = 'smpp';
    public const SOURCE_XML = 'xml';
    public const SOURCE_HTTP = 'http';
    public const SOURCE_JSON = 'json';
    public const STATUS_DELIVERED = 'Delivered';
    public const STATUS_REJECTED = 'Rejected';
    public const STATUS_SCHEDULED = 'Scheduled';
    public const STATUS_MODERATION = 'Moderation';
    public const STATUS_ACCEPTED = 'Accepted';
    public const STATUS_SENDING = 'Sending';
    public const STATUS_SENT = 'Sent';
    public const STATUS_EXPIRED = 'Expired';
    public const STATUS_FAILED = 'Failed';
    public const STATUS_UNDELIVERED = 'Undelivered';
    public const STATUS_UNKNOWN = 'Unknown';
    public const SL_CLICKS_COMP_EQUAL = '=';
    public const SL_CLICKS_COMP_GREATER_THAN = '>';
    public const SL_CLICKS_COMP_LESS_THAN = '<';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_MESSAGE,
            self::TYPE_PARAMS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSenderAllowableValues()
    {
        return [
            self::SENDER_API,
            self::SENDER_WEB,
            self::SENDER_SMPP,
            self::SENDER_XML,
            self::SENDER_HTTP,
            self::SENDER_JSON,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceAllowableValues()
    {
        return [
            self::SOURCE_API,
            self::SOURCE_WEB,
            self::SOURCE_SMPP,
            self::SOURCE_XML,
            self::SOURCE_HTTP,
            self::SOURCE_JSON,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_DELIVERED,
            self::STATUS_REJECTED,
            self::STATUS_SCHEDULED,
            self::STATUS_MODERATION,
            self::STATUS_ACCEPTED,
            self::STATUS_SENDING,
            self::STATUS_SENT,
            self::STATUS_EXPIRED,
            self::STATUS_FAILED,
            self::STATUS_UNDELIVERED,
            self::STATUS_UNKNOWN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSlClicksCompAllowableValues()
    {
        return [
            self::SL_CLICKS_COMP_EQUAL,
            self::SL_CLICKS_COMP_GREATER_THAN,
            self::SL_CLICKS_COMP_LESS_THAN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('message_id', $data ?? [], null);
        $this->setIfExists('time_in_from', $data ?? [], null);
        $this->setIfExists('time_in_to', $data ?? [], null);
        $this->setIfExists('time_sent_from', $data ?? [], null);
        $this->setIfExists('time_sent_to', $data ?? [], null);
        $this->setIfExists('phones', $data ?? [], null);
        $this->setIfExists('sender', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('operator_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('sl_clicks', $data ?? [], null);
        $this->setIfExists('sl_clicks_comp', $data ?? [], null);
        $this->setIfExists('sl_clicks_count', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['type'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['message_id'] === null) {
            $invalidProperties[] = "'message_id' can't be null";
        }
        if ($this->container['time_in_from'] === null) {
            $invalidProperties[] = "'time_in_from' can't be null";
        }
        if ($this->container['time_in_to'] === null) {
            $invalidProperties[] = "'time_in_to' can't be null";
        }
        $allowedValues = $this->getSenderAllowableValues();
        if (!is_null($this->container['sender']) && !in_array($this->container['sender'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sender', must be one of '%s'",
                $this->container['sender'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSourceAllowableValues();
        if (!is_null($this->container['source']) && !in_array($this->container['source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source', must be one of '%s'",
                $this->container['source'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSlClicksCompAllowableValues();
        if (!is_null($this->container['sl_clicks_comp']) && !in_array($this->container['sl_clicks_comp'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'sl_clicks_comp', must be one of '%s'",
                $this->container['sl_clicks_comp'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Job creation type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets message_id
     *
     * @return int[]
     */
    public function getMessageId()
    {
        return $this->container['message_id'];
    }

    /**
     * Sets message_id
     *
     * @param int[] $message_id Message Ids
     *
     * @return self
     */
    public function setMessageId($message_id)
    {
        if (is_null($message_id)) {
            throw new \InvalidArgumentException('non-nullable message_id cannot be null');
        }
        $this->container['message_id'] = $message_id;

        return $this;
    }

    /**
     * Gets time_in_from
     *
     * @return \DateTime
     */
    public function getTimeInFrom()
    {
        return $this->container['time_in_from'];
    }

    /**
     * Sets time_in_from
     *
     * @param \DateTime $time_in_from Datetime when messages were received on the platform
     *
     * @return self
     */
    public function setTimeInFrom($time_in_from)
    {
        if (is_null($time_in_from)) {
            throw new \InvalidArgumentException('non-nullable time_in_from cannot be null');
        }
        $this->container['time_in_from'] = $time_in_from;

        return $this;
    }

    /**
     * Gets time_in_to
     *
     * @return \DateTime
     */
    public function getTimeInTo()
    {
        return $this->container['time_in_to'];
    }

    /**
     * Sets time_in_to
     *
     * @param \DateTime $time_in_to Datetime when messages were received on the platform
     *
     * @return self
     */
    public function setTimeInTo($time_in_to)
    {
        if (is_null($time_in_to)) {
            throw new \InvalidArgumentException('non-nullable time_in_to cannot be null');
        }
        $this->container['time_in_to'] = $time_in_to;

        return $this;
    }

    /**
     * Gets time_sent_from
     *
     * @return \DateTime|null
     */
    public function getTimeSentFrom()
    {
        return $this->container['time_sent_from'];
    }

    /**
     * Sets time_sent_from
     *
     * @param \DateTime|null $time_sent_from Time of sending messages from the platform “from”
     *
     * @return self
     */
    public function setTimeSentFrom($time_sent_from)
    {
        if (is_null($time_sent_from)) {
            throw new \InvalidArgumentException('non-nullable time_sent_from cannot be null');
        }
        $this->container['time_sent_from'] = $time_sent_from;

        return $this;
    }

    /**
     * Gets time_sent_to
     *
     * @return \DateTime|null
     */
    public function getTimeSentTo()
    {
        return $this->container['time_sent_to'];
    }

    /**
     * Sets time_sent_to
     *
     * @param \DateTime|null $time_sent_to Time of sending messages from the platform “to”
     *
     * @return self
     */
    public function setTimeSentTo($time_sent_to)
    {
        if (is_null($time_sent_to)) {
            throw new \InvalidArgumentException('non-nullable time_sent_to cannot be null');
        }
        $this->container['time_sent_to'] = $time_sent_to;

        return $this;
    }

    /**
     * Gets phones
     *
     * @return int[]|null
     */
    public function getPhones()
    {
        return $this->container['phones'];
    }

    /**
     * Sets phones
     *
     * @param int[]|null $phones phone list
     *
     * @return self
     */
    public function setPhones($phones)
    {
        if (is_null($phones)) {
            throw new \InvalidArgumentException('non-nullable phones cannot be null');
        }
        $this->container['phones'] = $phones;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return string|null
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param string|null $sender Source from where the message came to the platform
     *
     * @return self
     */
    public function setSender($sender)
    {
        if (is_null($sender)) {
            throw new \InvalidArgumentException('non-nullable sender cannot be null');
        }
        $allowedValues = $this->getSenderAllowableValues();
        if (!in_array($sender, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sender', must be one of '%s'",
                    $sender,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source Source from where the message came to the platform
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $allowedValues = $this->getSourceAllowableValues();
        if (!in_array($source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source', must be one of '%s'",
                    $source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country The name of the country for search
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets operator_id
     *
     * @return string|null
     */
    public function getOperatorId()
    {
        return $this->container['operator_id'];
    }

    /**
     * Sets operator_id
     *
     * @param string|null $operator_id Indication of the country operator
     *
     * @return self
     */
    public function setOperatorId($operator_id)
    {
        if (is_null($operator_id)) {
            throw new \InvalidArgumentException('non-nullable operator_id cannot be null');
        }
        $this->container['operator_id'] = $operator_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The status of the messages to display
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets sl_clicks
     *
     * @return string|null
     */
    public function getSlClicks()
    {
        return $this->container['sl_clicks'];
    }

    /**
     * Sets sl_clicks
     *
     * @param string|null $sl_clicks The field is available only to the clients who have enabled Short URL service
     *
     * @return self
     */
    public function setSlClicks($sl_clicks)
    {
        if (is_null($sl_clicks)) {
            throw new \InvalidArgumentException('non-nullable sl_clicks cannot be null');
        }
        $this->container['sl_clicks'] = $sl_clicks;

        return $this;
    }

    /**
     * Gets sl_clicks_comp
     *
     * @return string|null
     */
    public function getSlClicksComp()
    {
        return $this->container['sl_clicks_comp'];
    }

    /**
     * Sets sl_clicks_comp
     *
     * @param string|null $sl_clicks_comp Comparison operator with the clicks count value
     *
     * @return self
     */
    public function setSlClicksComp($sl_clicks_comp)
    {
        if (is_null($sl_clicks_comp)) {
            throw new \InvalidArgumentException('non-nullable sl_clicks_comp cannot be null');
        }
        $allowedValues = $this->getSlClicksCompAllowableValues();
        if (!in_array($sl_clicks_comp, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'sl_clicks_comp', must be one of '%s'",
                    $sl_clicks_comp,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['sl_clicks_comp'] = $sl_clicks_comp;

        return $this;
    }

    /**
     * Gets sl_clicks_count
     *
     * @return string|null
     */
    public function getSlClicksCount()
    {
        return $this->container['sl_clicks_count'];
    }

    /**
     * Sets sl_clicks_count
     *
     * @param string|null $sl_clicks_count Comparison operator with the clicks count value
     *
     * @return self
     */
    public function setSlClicksCount($sl_clicks_count)
    {
        if (is_null($sl_clicks_count)) {
            throw new \InvalidArgumentException('non-nullable sl_clicks_count cannot be null');
        }
        $this->container['sl_clicks_count'] = $sl_clicks_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


